language: objective-c
xcode_project: HypertextApplicationLanguage.xcodeproj
xcode_scheme: HypertextApplicationLanguage
osx_image: xcode7.1

# Important to specify the simulator SDK, otherwise Travis CI will attempt to
# build for the real iPhone and fail due to code-signing issues.
xcode_sdk: iphonesimulator9.1

before_install:
  - brew update
  - brew uninstall xctool && brew install --HEAD xctool
